org.gradle.jvmargs=-Xmx8G -XX:MaxMetaspaceSize=4G -XX:ReservedCodeCacheSize=512m -XX:+HeapDumpOnOutOfMemoryError
android.useAndroidX=true
# This newDsl flag was added by the Flutter template
android.newDsl=false
# This builtInKotlin flag was added by the Flutter template
android.builtInKotlin=false
org.gradle.jvmargs=-Xmx3g -Djava.net.preferIPv4Stack=true -XX:MaxMetaspaceSize=512m
systemProp.http.proxyHost=hatch-egress-proxy
systemProp.http.proxyPort=3128
systemProp.https.proxyHost=hatch-egress-proxy
systemProp.https.proxyPort=3128
systemProp.http.nonProxyHosts=localhost|127.0.0.1
systemProp.https.nonProxyHosts=localhost|127.0.0.1
